services:

  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    container_name: warracker
    ports:
      - "8200:80"
    volumes:
      - ./warracker_uploads:/data/uploads
    environment:
      - DB_HOST=warrackerdb
      - DB_PORT=5432
      - DB_NAME=warranty_db
      - DB_USER=warranty_user
      - DB_PASSWORD=warranty_password
      - SMTP_HOST=smtp.email.com
      - SMTP_PORT=465
      - SMTP_USERNAME=youremail@email.com
      - SMTP_PASSWORD=password
      - SECRET_KEY=your_strong_default_secret_key_here 
      - MAX_UPLOAD_MB=32
    depends_on:
      warrackerdb:
        condition: service_healthy
    restart: unless-stopped

  warrackerdb:
    image: postgres:15-alpine
    container_name: warracker_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=warranty_db
      - POSTGRES_USER=warranty_user
      - POSTGRES_PASSWORD=warranty_password
    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warranty_user -d warranty_db"]
      interval: 5s
      timeout: 5s
      retries: 5
